name: Build tvOS

on: [pull_request, workflow_dispatch]

jobs:
  tvos:
    name: tvOS (build)

    strategy:
      matrix:
        platform: [macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@master

      - name: Github actions bundle cache
        uses: actions/cache@v1
        with:
          path: .vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Github actions cocoapods cache
        uses: actions/cache@v1
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/**Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.3'

      - name: Install yarn globally
        run: |
          npm install -g yarn
          yarn config set network-timeout 300000

      - name: Run yarn install
        run: |
          yarn install --frozen-lockfile
          rm -f .npmrc

      - name: Install bundler and run bundle install
        run: |
          gem install bundler:2.1.4
          bundle config path .vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Install CocoaPods
        run: |
          bundle exec pod --version
          yarn pods-noupdate

      - name: Build
        run: |
          xcodebuild -workspace ./ios/shapeshifter.xcworkspace -scheme shapeshifter
